name: prisma_generator_helper
description: >-
  Prisma generator helper to quickly build Prisma generators.
version: 1.2.4
repository: https://github.com/odroe/prisma-generator-helper

funding:
  - https://github.com/sponsors/odroe
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_rpc_2: ^3.0.2
  stream_channel: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  lints: ^2.0.1
  test: ^1.16.0
