name: prisma_generator_helper
description: >-
  Prisma generator helper to quickly build Prisma generators.
version: 1.1.0
repository: https://github.com/odroe/prisma-generator-helper

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_rpc_2: ^3.0.2
  stream_channel: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.16.0
