name: prisma_generator_helper
description: Auxiliary packages to help quickly build Prisma generators.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  json_annotation: ^4.8.0
  json_rpc_2: ^3.0.2
  prisma_dmmf: ^1.0.0
  stream_channel: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.16.0
